"""GStreamer / DeepStream ingest pipelines.

Two levels of integration, both yielding the same ``(ts, frame_bgr)`` stream
as ``rtsp_client.FrameSource`` so the rest of the pipeline is agnostic:

1. **Plain GStreamer appsink** (`GStreamerSource`) — hardware-decoded RTSP on
   any box with PyGObject installed; on Jetson the pipeline string uses NVMM
   decoding (``nvv4l2decoder``).
2. **DeepStream** — for many-camera GPU batching, run detection *inside*
   DeepStream (``nvurisrcbin → nvstreammux → nvinfer(YOLO26 TensorRT) →
   nvtracker(ByteTrack)``) and feed this app's Stage 2+ from a probe. The
   reference pipeline string is generated by :func:`deepstream_pipeline_desc`;
   attaching the metadata probe is deployment-specific (see NVIDIA
   deepstream_python_apps). Until then the appsink path covers Jetson too.
"""

from __future__ import annotations

import logging
import time
from typing import Iterator

import numpy as np

logger = logging.getLogger(__name__)


def gst_pipeline_desc(uri: str, jetson: bool = False, latency_ms: int = 100) -> str:
    """Appsink pipeline string: RTSP → HW/SW decode → BGR appsink."""
    if jetson:
        return (
            f'rtspsrc location="{uri}" latency={latency_ms} protocols=tcp ! '
            "rtph264depay ! h264parse ! nvv4l2decoder ! "
            "nvvidconv ! video/x-raw,format=BGRx ! videoconvert ! "
            "video/x-raw,format=BGR ! appsink name=sink drop=true max-buffers=2 sync=false"
        )
    return (
        f'uridecodebin uri="{uri}" ! videoconvert ! video/x-raw,format=BGR ! '
        "appsink name=sink drop=true max-buffers=2 sync=false"
    )


def deepstream_pipeline_desc(uris: list[str], batch_size: int | None = None,
                             infer_config: str = "configs/ds_yolo26_pgie.txt",
                             tracker_config: str = "configs/ds_bytetrack.yml") -> str:
    """Reference DeepStream description for multi-camera batched Stage 1."""
    batch = batch_size or len(uris)
    srcs = " ".join(
        f'nvurisrcbin uri="{u}" ! mux.sink_{i}' for i, u in enumerate(uris))
    return (
        f"{srcs} nvstreammux name=mux batch-size={batch} width=1280 height=720 "
        f"batched-push-timeout=40000 ! nvinfer config-file-path={infer_config} ! "
        f"nvtracker ll-config-file={tracker_config} ! nvvideoconvert ! "
        f"nvdsosd ! fakesink sync=false"
    )


class GStreamerSource:
    """Appsink-based frame source (same contract as rtsp_client.FrameSource)."""

    def __init__(self, camera_id: str, source: str, jetson: bool = False, **_):
        try:
            import gi
            gi.require_version("Gst", "1.0")
            from gi.repository import Gst
        except (ImportError, ValueError) as exc:
            raise ImportError(
                "GStreamer ingest needs PyGObject + GStreamer "
                "(apt install python3-gi gstreamer1.0-plugins-{base,good,bad})"
            ) from exc
        self._Gst = Gst
        Gst.init(None)
        self.camera_id = camera_id
        self.is_live = True
        self.fps = 25.0
        uri = source if "://" in source else f"file://{source}"
        self._pipeline = Gst.parse_launch(gst_pipeline_desc(uri, jetson=jetson))
        self._sink = self._pipeline.get_by_name("sink")
        self._sink.set_property("emit-signals", False)

    def frames(self) -> Iterator[tuple[float, np.ndarray]]:
        Gst = self._Gst
        self._pipeline.set_state(Gst.State.PLAYING)
        t0 = time.monotonic()
        logger.info("[%s] GStreamer pipeline playing", self.camera_id)
        try:
            while True:
                sample = self._sink.emit("try-pull-sample", Gst.SECOND)
                if sample is None:
                    if self._sink.get_property("eos"):
                        return
                    continue
                buf = sample.get_buffer()
                caps = sample.get_caps().get_structure(0)
                h, w = caps.get_value("height"), caps.get_value("width")
                ok, info = buf.map(Gst.MapFlags.READ)
                if not ok:
                    continue
                try:
                    frame = np.frombuffer(info.data, dtype=np.uint8).reshape(h, w, 3).copy()
                finally:
                    buf.unmap(info)
                yield time.monotonic() - t0, frame
        finally:
            self._pipeline.set_state(Gst.State.NULL)
